export const TemplateHeader = [
  {
    field: 'field_name',
    headerName: 'Field Name',
    width: 180,
    editable: true,
    type: '',
    // renderEditCell: renderSelectEditInputCell
  },
  { field: 'alias_name', headerName: 'Alais Name', type: 'number', editable: true },
  {
    field: 'g_templateType',
    headerName: 'Type of Field',
    type: 'date',
    width: 180,
    editable: true,
  },
  {
    field: 'comment',
    headerName: 'Comment',
    type: 'dateTime',
    width: 220,
    editable: true,
  },
  {
    field: 'send_trigger',
    headerName: 'Send Trigger (Y/N)',
    type: 'dateTime',
    width: 220,
    editable: true,
  },
  {
    field: 'data',
    headerName: 'Trigger Message',
    type: 'dateTime',
    width: 220,
    editable: true,
  },
  {
    field: 'param',
    headerName: 'Params',
    type: 'dateTime',
    width: 220,
    editable: true,
  },
  {
    field: 'button',
    headerName: 'Buttons',
    type: 'dateTime',
    width: 220,
    editable: true,
  },
  {
    field: 'lastLogin',
    headerName: 'Action',
    type: 'dateTime',
    width: 220,
    editable: true,
  },
];
