// Appearance
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

// Auth
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Checklist
export const POST_CHECKLIST_TEMPLATE_START = 'POST_CHECKLIST_TEMPLATE_START';
export const POST_CHECKLIST_TEMPLATE_SUCCESS =
  'POST_CHECKLIST_TEMPLATE_SUCCESS';
export const POST_CHECKLIST_TEMPLATE_FAIL = 'POST_CHECKLIST_TEMPLATE_FAIL';
export const GET_SUPPLIER_CHECKLISTS_START = 'GET_SUPPLIER_CHECKLISTS_START';
export const GET_SUPPLIER_CHECKLISTS_SUCCESS =
  'GET_SUPPLIER_CHECKLISTS_SUCCESS';
export const GET_SUPPLIER_CHECKLISTS_FAIL = 'GET_SUPPLIER_CHECKLISTS_FAIL';
export const DELETE_SUPPLIER_CHECKLIST_START =
  'DELETE_SUPPLIER_CHECKLIST_START';
export const DELETE_SUPPLIER_CHECKLIST_SUCCESS =
  'DELETE_SUPPLIER_CHECKLIST_SUCCESS';
export const DELETE_SUPPLIER_CHECKLIST_FAIL = 'DELETE_SUPPLIER_CHECKLIST_FAIL';

// Campaign
export const GET_CAMPAIGNS_LIST_START = 'GET_CAMPAIGNS_LIST_START';
export const GET_CAMPAIGNS_LIST_SUCCESS = 'GET_CAMPAIGNS_LIST_SUCCESS';
export const GET_CAMPAIGNS_LIST_FAIL = 'GET_CAMPAIGNS_LIST_FAIL';

// Supplier
export const GET_SUPPLIERS_LIST_START = 'GET_SUPPLIERS_LIST_START';
export const GET_SUPPLIERS_LIST_SUCCESS = 'GET_SUPPLIERS_LIST_SUCCESS';
export const GET_SUPPLIERS_LIST_FAIL = 'GET_SUPPLIERS_LIST_FAIL';
