// Appearance
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

// Auth
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Checklist
//Create Template
export const POST_CHECKLIST_TEMPLATE_START = 'POST_CHECKLIST_TEMPLATE_START';
export const POST_CHECKLIST_TEMPLATE_SUCCESS =
  'POST_CHECKLIST_TEMPLATE_SUCCESS';
export const POST_CHECKLIST_TEMPLATE_FAIL = 'POST_CHECKLIST_TEMPLATE_FAIL';

//Update Template
export const UPDATE_CHECKLIST_TEMPLATE_START =
  'UPDATE_CHECKLIST_TEMPLATE_START';
export const UPDATE_CHECKLIST_TEMPLATE_SUCCESS =
  'UPDATE_CHECKLIST_TEMPLATE_SUCCESS';
export const UPDATE_CHECKLIST_TEMPLATE_FAIL = 'UPDATE_CHECKLIST_TEMPLATE_FAIL';

//Get Checklist List
export const GET_CHECKLISTS_START = 'GET_CHECKLISTS_START';
export const GET_CHECKLISTS_SUCCESS = 'GET_CHECKLISTS_SUCCESS';
export const GET_CHECKLISTS_FAIL = 'GET_CHECKLISTS_FAIL';

//Get Checklist Template List
export const GET_CHECKLIST_TEMPLATE_LIST_START =
  'GET_CHECKLIST_TEMPLATE_LIST_START';
export const GET_CHECKLIST_TEMPLATE_LIST_SUCCESS =
  'GET_CHECKLIST_TEMPLATE_LIST_SUCCESS';
export const GET_CHECKLIST_TEMPLATE_LIST_FAIL =
  'GET_CHECKLIST_TEMPLATE_LIST_FAIL';

//Delete Checklist
export const DELETE_CHECKLIST_START = 'DELETE_CHECKLIST_START';
export const DELETE_CHECKLIST_SUCCESS = 'DELETE_CHECKLIST_SUCCESS';
export const DELETE_CHECKLIST_FAIL = 'DELETE_CHECKLIST_FAIL';

//Get Single Checklist
export const GET_SINGLE_CHECKLIST_START = 'GET_SINGLE_CHECKLIST_START';
export const GET_SINGLE_CHECKLIST_SUCCESS = 'GET_SINGLE_CHECKLIST_SUCCESS';
export const GET_SINGLE_CHECKLIST_FAIL = 'GET_SINGLE_CHECKLIST_FAIL';

//Fill Checklist
export const POST_CHECKLIST_ENTRIES_START = 'POST_CHECKLIST_ENTRIES_START';
export const POST_CHECKLIST_ENTRIES_SUCCESS = 'POST_CHECKLIST_ENTRIES_SUCCESS';
export const POST_CHECKLIST_ENTRIES_FAIL = 'POST_CHECKLIST_ENTRIES_FAIL';

// Campaign
export const GET_CAMPAIGNS_LIST_START = 'GET_CAMPAIGNS_LIST_START';
export const GET_CAMPAIGNS_LIST_SUCCESS = 'GET_CAMPAIGNS_LIST_SUCCESS';
export const GET_CAMPAIGNS_LIST_FAIL = 'GET_CAMPAIGNS_LIST_FAIL';

// Current Campaign
export const GET_CURRENT_CAMPAIGN_START = 'GET_CURRENT_CAMPAIGN_START';
export const GET_CURRENT_CAMPAIGN_SUCCESS = 'GET_CURRENT_CAMPAIGN_SUCCESS';
export const GET_CURRENT_CAMPAIGN_FAIL = 'GET_CURRENT_CAMPAIGN_FAIL';

// Supplier List
export const GET_SUPPLIERS_LIST_START = 'GET_SUPPLIERS_LIST_START';
export const GET_SUPPLIERS_LIST_SUCCESS = 'GET_SUPPLIERS_LIST_SUCCESS';
export const GET_SUPPLIERS_LIST_FAIL = 'GET_SUPPLIERS_LIST_FAIL';

// Current Supplier
export const GET_CURRENT_SUPPLIER_START = 'GET_CURRENT_SUPPLIER_START';
export const GET_CURRENT_SUPPLIER_SUCCESS = 'GET_CURRENT_SUPPLIER_SUCCESS';
export const GET_CURRENT_SUPPLIER_FAIL = 'GET_CURRENT_SUPPLIER_FAIL';

//Post Entity Type
export const POST_ENTITY_TYPE_START = 'POST_ENTITY_TYPE_START';
export const POST_ENTITY_TYPE_SUCCESS = 'POST_ENTITY_TYPE_SUCCESS';
export const POST_ENTITY_TYPE_FAIL = 'POST_ENTITY_TYPE_FAIL';

//Post Entity
export const POST_ENTITY_START = 'POST_ENTITY_START';
export const POST_ENTITY_SUCCESS = 'POST_ENTITY_SUCCESS';
export const POST_ENTITY_FAIL = 'POST_ENTITY_FAIL';

//Get Entity List
export const GET_ENTITY_TYPE_LIST_START = 'GET_ENTITY_TYPE_LIST_START';
export const GET_ENTITY_TYPE_LIST_SUCCESS = 'GET_ENTITY_TYPE_LIST_SUCCESS';
export const GET_ENTITY_TYPE_LIST_FAIL = 'GET_ENTITY_TYPE_LIST_FAIL';

//Get Permission List
export const GET_PERMISSION_LIST_START = 'GET_PERMISSION_LIST_START';
export const GET_PERMISSION_LIST_SUCCESS = 'GET_PERMISSION_LIST_SUCCESS';
export const GET_PERMISSION_LIST_FAIL = 'GET_PERMISSION_LIST_FAIL';

//Get User Permission
export const GET_USER_PERMISSION_START = 'GET_USER_PERMISSION_START';
export const GET_USER_PERMISSION_SUCCESS = 'GET_USER_PERMISSION_SUCCESS';
export const GET_USER_PERMISSION_FAIL = 'GET_USER_PERMISSION_FAIL';

// User List
export const GET_USERS_LIST_START = 'GET_USERS_LIST_START';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAIL = 'GET_USERS_LIST_FAIL';

// //Get Lead Permission List
export const GET_LEAD_PERMISSION_LIST_START = 'GET_LEAD_PERMISSION_LIST_START';
export const GET_LEAD_PERMISSION_LIST_SUCCESS =
  'GET_LEAD_PERMISSION_LIST_SUCCESS';
export const GET_LEAD_PERMISSION_LIST_FAIL = 'GET_LEAD_PERMISSION_LIST_FAIL';

//Get Lead User Permission
export const GET_LEAD_USER_PERMISSION_START = 'GET_LEAD_USER_PERMISSION_START';
export const GET_LEAD_USER_PERMISSION_SUCCESS =
  'GET_LEAD_USER_PERMISSION_SUCCESS';
export const GET_LEAD_USER_PERMISSION_FAIL = 'GET_LEAD_USER_PERMISSION_FAIL';

//Get Logged In User Permission
export const GET_LOGGED_IN_USER_PERMISSION_START =
  'GET_LOGGED_IN_USER_PERMISSION_START';
export const GET_LOGGED_IN_USER_PERMISSION_SUCCESS =
  'GET_LOGGED_IN_USER_PERMISSION_SUCCESS';
export const GET_LOGGED_IN_USER_PERMISSION_FAIL =
  'GET_LOGGED_IN_USER_PERMISSION_FAIL';

//Post Base Inventory
export const POST_BASE_INVENTORY_START = 'POST_BASE_INVENTORY_START';
export const POST_BASE_INVENTORY_SUCCESS = 'POST_BASE_INVENTORY_SUCCESS';
export const POST_BASE_INVENTORY_FAIL = 'POST_BASE_INVENTORY_FAIL';

//GET Base Inventory
export const GET_BASE_INVENTORY_START = 'GET_BASE_INVENTORY_START';
export const GET_BASE_INVENTORY_SUCCESS = 'GET_BASE_INVENTORY_SUCCESS';
export const GET_BASE_INVENTORY_FAIL = 'GET_BASE_INVENTORY_FAIL';

//DELETE Base Inventory
export const DELETE_BASE_INVENTORY_START = 'DELETE_BASE_INVENTORY_START';
export const DELETE_BASE_INVENTORY_SUCCESS = 'DELETE_BASE_INVENTORY_SUCCESS';
export const DELETE_BASE_INVENTORY_FAIL = 'DELETE_BASE_INVENTORY_FAIL';
