// Appearance
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

// Auth
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Checklist
export const POST_CHECKLIST_TEMPLATE_START = 'POST_CHECKLIST_TEMPLATE_START';
export const POST_CHECKLIST_TEMPLATE_SUCCESS =
  'POST_CHECKLIST_TEMPLATE_SUCCESS';
export const POST_CHECKLIST_TEMPLATE_FAIL = 'POST_CHECKLIST_TEMPLATE_FAIL';

// Campaigns
export const GET_CAMPAIGNS_LIST_START = 'GET_CAMPAIGNS_LIST_START';
export const GET_CAMPAIGNS_LIST_SUCCESS = 'GET_CAMPAIGNS_LIST_SUCCESS';
export const GET_CAMPAIGNS_LIST_FAIL = 'GET_CAMPAIGNS_LIST_FAIL';
